# Generated by Django 5.0.2 on 2024-02-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('lvlxp', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('cosmetics', models.CharField(max_length=1000)),
                ('achievements', models.CharField(max_length=1000)),
                ('tasks', models.CharField(max_length=1000)),
            ],
        ),
    ]
