# Generated by Django 5.0.2 on 2024-02-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_task_alter_user_cosmetics_remove_user_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='user',
            name='cosmetics',
            field=models.CharField(max_length=1000),
        ),
    ]
