# Generated by Django 5.0.2 on 2024-02-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_tasks_alter_user_cosmetics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
