# Generated by Django 5.0.2 on 2024-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='cosmetics',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
