# Generated by Django 5.0.1 on 2024-02-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_tasks_alter_user_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bronze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='highRoller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='newbie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='silver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='taskCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gold',
            field=models.BooleanField(default=False),
        ),
    ]
