# Generated by Django 5.0.2 on 2024-02-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_bronze_user_highroller_user_newbie_user_silver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bronze',
            new_name='bronzeMedal',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='silver',
            new_name='goldMedal',
        ),
        migrations.AddField(
            model_name='user',
            name='silverMedal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gold',
            field=models.IntegerField(),
        ),
    ]
